### ISSUE TITLE
Be able to execute one of the strava functions using a web page

### ISSUE THREAD

**Issue by mvillis** [brendonc83/stravamate#1]
* Simple input / output page. 
* hardcore user token for auth to strava

**Comment by brendonc83** [comment]
The definition of done for this card includes:

* A functional test for displaying Strava athlete stats. This will validate the user experience and validate the total distance ridden for the athlete
* A unit test for displaying the stats. It will validate the total distance ridden for the athlete
* The creation of a page that will display my Strava Athlete stats
* Bootstrap integration
* Tests passing locally

**Comment by brendonc83** [comment]
All acceptance criteria for this card are now complete. Both unit test and functional test are passing in travis. The pull request has been merged.

**Comment by mvillis** [comment]
Nice work :+1:
